### ISSUE TITLE
Recursion Issue

### ISSUE THREAD

**Issue by woodwardtw** [vcualtlab/motherblog#5]
When the blog admin ties one of their other rampages blogs into the mother blog it makes them (admin) into a subscriber.

Example (in case that's not clear): Monte was the admin for TEDU 600. He wanted to tie in his personal blog (also on rampages). Once he joined it made him a subscriber instead of an admin.

**Comment by luetkemj** [comment]
Use [is_user_member_of_blog()](https://codex.wordpress.org/WPMU_Functions/is_user_member_of_blog) inside of [add_current_user_to_mother_blog()](https://github.com/vcualtlab/motherblog/blob/master/admin/class-altlab-motherblog-admin.php#L280) to check if current user is already a member of the mother blog.

**Comment by luetkemj** [comment]
Fixed
