### ISSUE TITLE
Links not getting associated with FWP category

### ISSUE THREAD

**Issue by luetkemj** [vcualtlab/motherblog#6]
Sometimes this happens... I manually added the contributors category to one of the links and it showed up in FWP and then everything started to work properly. So maybe we just have to kickstart the process?

**Comment by woodwardtw** [comment]
Just experienced the same thing. For anyone wondering, you'd do this under "Links" in the dashboard. Once you add the contributor it'll show up under Syndication like you'd expect.

**Comment by woodwardtw** [comment]
This should be fixed now.

**Comment by luetkemj** [comment]
👯
